### ISSUE TITLE
Update ping notifications in DMs

### ISSUE THREAD

**Issue by scioly** [cbrxyz/pi-bot#119]
It'd be helpful if ping notifications could include the channel in which the message was sent. When I come back after a while and have many ping notifications, I tend to get lost as I'm scrolling through them especially because I have a small number of frequently used pings by the same people usually so the notifications are very similar.

**Comment by cbrxyz** [comment]
Good idea! Changed the title so that this issue encompasses other fields that can be added to the DM notifications, such as the original message
