### ISSUE TITLE
Make the appearance of square-root function for !fish more prominent

### ISSUE THREAD

**Issue by kleinerPanzer** [cbrxyz/pi-bot#150]
Considering how fast people spam "!fish", it's often hard to immediately see when the fish has been square-rooted. Adding a bit of color (an emoji) or an extra line would help be visually distinct, at a glance, from the standard +1, +10, or +0 as it is very impactful on the number of fish.

**Comment by scioly** [comment]
I'd like to suggest an appearance.

> 😭
> 😭
> 😭
> Aww, bear's fish was accidentally square root'ed. Bear now has 7523 fish.
> 😭
> 😭
> 😭
