### ISSUE TITLE
`!unban` runs into an error and does not unban the user

### ISSUE THREAD

**Issue by scioly** [cbrxyz/pi-bot#168]
`!unban` does not work. Yes, I read the help this time! (Cue `!treat`...) `!ban` works but `!unban` doesn't.

<img width="605" alt="Screen Shot 2020-09-20 at 21 19 26" src="https://user-images.githubusercontent.com/7704722/93732684-42e9d980-fb87-11ea-9ca2-563c0892f885.png">

**Comment by Nydauron** [comment]
`!unban <id>` on the master branch does successfully unban the user. I'm guessing you had a space after the ID which caused the error.

However, I did notice no invite is sent to the unbanned user. This will be fixed up.
Also, the mention parameter is more user-friendly, so I'll try to find a way to use either param.

**Comment by Nydauron** [comment]
Regarding the invites, no DMs can be sent to users outside of the server (for obvious security purposes). So, I'm not totally sure why we need to create an invite at all.

Either way, the command now supports @ing a user as well for quick unbans instead of having to get the ID of the user. Will make a PR on this soon.

**Comment by scioly** [comment]
@Nydauron unban still isn't working for me. I've checked for excess whitespace and the ID specified is indeed the user's ID: `!unban 748078352635789382`.

**Comment by Nydauron** [comment]
@scioly is this on the current master or on the current deployed version?

**Comment by scioly** [comment]
@Nydauron I ran my tests in the server so currently deployed version.

**Comment by cbrxyz** [comment]
Solution solved.

```py
@bot.command()
@commands.check(isStaff)
async def unban(ctx, id:int=0):
    """Unbans a user."""
    if id == 0:
        await ctx.channel.send("Please give a user ID.")
        return
    invite = await ctx.channel.create_invite(max_age = 86400) # the bot can not create invites, since there are special invites used to track stats
    member = await bot.fetch_user(id)
    await ctx.guild.unban(member)
    await ctx.channel.send(f"Inverse ban hammer applied, user unbanned. Please remember that I cannot force them to re-join the server, they must join themselves.")
```

The bot can not create invites, because there are special invites used to track server stats. Thus, it fails and can't run the rest of the command!

**Comment by Nydauron** [comment]
Ahh yes, makes sense that it was a perms issue. Unfortunately, I didn't know what its perms are on the server, so good catch! Close #168.

**Comment by scioly** [comment]
Oh well, not a big deal as we rarely ban users and even more rarely unban users. This can be handled manually as needed.
