### ISSUE TITLE
Pings are not case sensitive but adding/removing pings is

### ISSUE THREAD

**Issue by kleinerPanzer** [cbrxyz/pi-bot#239]
![image](https://user-images.githubusercontent.com/70746595/96820604-f561c600-13eb-11eb-933c-1bc738701250.png)

**Comment by scioly** [comment]
I think this is what is vaguely described by #115.

**Comment by kleinerPanzer** [comment]
> I think this is what is vaguely described by #115.

ah whoops. shouldn't bug-report while sleep-deprived, i suppose
