### ISSUE TITLE
!selfmute 1hr lasts no longer than 1 minute

### ISSUE THREAD

**Issue by qedgary** [cbrxyz/pi-bot#242]
When a user types **!selfmute 2hr** at 19:59 EST, Pi-Bot states **Successfully muted someUser until `2020-10-23 21:59:31.012354 EST`**, but the mute is automatically lifted no more than 1 minute after the self-mute. The same thing is occurring when I type **!mute someUser 2hr**.

**Comment by cbrxyz** [comment]
Thanks for the report.

Problem:
To make it easier on users, the time that a user was muted until was stored in EST. The bot uses UTC.

So when a user is muted until `11:59PM EST` at `9:59PM EST`, the bot already thinks the mute is over, because it's time is `1:59AM UTC`, and `1:59AM > 11:59PM`.
