### ISSUE TITLE
#tournaments channel not updating with number of votes

### ISSUE THREAD

**Issue by qedgary** [cbrxyz/pi-bot#295]
When a user types `!tournaments existing-tournament`, the list of tournaments does not increment in vote counts.

It is worth noting that the vote is counted correctly—that is, if the same user types the command again, they will receive a message stating that they already voted for that channel, or if another user adds the tournament, Pi-Bot correctly increments the count in the message "There are now `n+1` votes for this channel."

**Comment by cbrxyz** [comment]
Likely an issue with today's outage, but will check to make sure

**Comment by cbrxyz** [comment]
Indeed, thanks!
