### ISSUE TITLE
Add users who self mute to channel with button to un-selfmute

### ISSUE THREAD

**Issue by cbrxyz** [cbrxyz/pi-bot#325]
This will allow them to control their mute easier

**Comment by Nydauron** [comment]
Will need to create a new role "Self Mute" or equivalent to distinguish from those who are muted by mods or Pi-Bot.

**Comment by cbrxyz** [comment]
> Will need to create a new role "Self Mute" or equivalent to distinguish from those who are muted by mods or Pi-Bot.

That's definitely one way to do it, and I think doing it this way would also provide the benefit of seeing who has been muted for breaking rules vs. by choice.
