### ISSUE TITLE
Cron list should be editable/viewable by staff

### ISSUE THREAD

**Issue by cbrxyz** [cbrxyz/pi-bot#379]
The current state of the CRON list should be viewable and editable by staff, so that they can add cron tasks and remove them as needed.

A staff can run a command to get a table of the cron list, like so:
```
+----------+-----------------------+--------------------------------------------+
+ User 1   | Muted                 | 8 days, 1 hour (April 1, 2020 12:42 AM)    |
+----------+-----------------------+--------------------------------------------+
+ User 2   | Self-Muted            | 11 days, 5 hours (April 4, 2020 4:42 AM)   |
+----------+-----------------------+--------------------------------------------+
```

**Comment by pandabear189** [comment]
@bot.command()
@commands.check(is_staff)
async def removeVariable(ctx, user:discord.User):
    for obj in CRON_LIST[:]:
        if obj['do'] == f'unmute {user.id}':
            CRON_LIST.remove(obj)
            await ctx.send(f'Removed {user} unmute from CRON_LIST')
        elif obj['do'] == f'unban {user.id}':
            CRON_LIST.remove(obj)
            await ctx.send(f'Removed {user} unban from CRON_LIST')
        else:
            await ctx.send('Unknown object to remove')
            
       maybe something like this? its not exactly editing but it will remove unmutes and unbans...

**Comment by cbrxyz** [comment]
Hey Eric, that's not a bad idea!

I like your use of tablulate, the table doesn't look too bad! I bet if it's put in a code block (```) then it will look nicer too, since that has monospace.

**Comment by pandabear189** [comment]
hmm ill try that

**Comment by pandabear189** [comment]
![image](https://user-images.githubusercontent.com/88685021/133952425-e5049e57-c170-427b-984f-f37c9fa7b14b.png)
it looks great wow
