### ISSUE TITLE
Error with events command

### ISSUE THREAD

**Issue by pandabear189** [cbrxyz/pi-bot#393]
Recently the !events command hasn't been working and giving the error *Apologies... refreshing data currently. Try again in a few seconds.*
The censor has somehow also broke

**Comment by georgemsun** [comment]
Thanks for helping report issues, @pandabear189! ☺️

**Comment by cbrxyz** [comment]
Okay, thanks for the issue. I think this is connected to Google Sheets, which I have some plans to get around. I'll look into this soon 👍

**Comment by pandabear189** [comment]
not sure if this is related (probably is) because it dumps ping info to google sheets but all pings have been cleared

**Comment by cbrxyz** [comment]
Fixed.
