### ISSUE TITLE
Ping list doesn't update

### ISSUE THREAD

**Issue by qedgary** [cbrxyz/pi-bot#418]
When users add or remove pings, their changes get reset at a later point (at least a few hours later, maybe even a day). So, if a user says `!ping add "hand potato"`, then the ping will be registered for a while, but then a day later, it won't appear on the user's ping list. The earliest known instance of this resetting behavior is December 21.

**Comment by cbrxyz** [comment]
Thanks! I'll take a look at this as v5 is implemented and a new database system is put in place.

**Comment by cbrxyz** [comment]
This will be fixed in version 5!

**Comment by cbrxyz** [comment]
This has been fixed in v5.
