### ISSUE TITLE
Limit !nofish use

### ISSUE THREAD

**Issue by cbrxyz** [cbrxyz/pi-bot#90]
Limit the ability of a user to use `!nofish` repeatedly.

**Comment by scioly** [comment]
I think a reasonable limitation could be once every hour.

**Comment by cbrxyz** [comment]
`!nofish` was removed in 899fbaf in favor of `!stealfish`, which instead halves bear's fish in half.

Limitations on `!stealfish` can be added later.

**Comment by cbrxyz** [comment]
Not needed anymore
